version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"  # 06:00 UTC will be 08:00 in (GMT+2) timezone
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      # Example usage of "ignore:" key
      #- dependency-name: "aws*"
      #- dependency-name: "express"
      #  versions: ["4.x", "5.x"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "terraform"
    directory: "/terraform-infrastructure/argocd"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "terraform"
    directory: "/terraform-infrastructure/eks"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "terraform"
    directory: "/terraform-infrastructure/vpc"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
