services:
  todo:
    image: "${TESTING_IMAGE}"
#     ports:
#       - "80:80"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: "5s"

  service1:
    image: "${TESTING_IMAGE}"
#     ports:
#       - "80:80"
    depends_on:
      todo:
        condition: service_healthy
      postgres:
        condition: service_started  # TODO change to "service_healthy" after fixing the bug
    command: curl --fail http://todo:80 || exit 1

# volumes:
#   postgres_data: {}
