appName: golden-devops-helm-release

configmap:
  name: golden-devops-helm-release-configmap-v1
  data:
    CUSTOM_HEADER: "This app was deployed with helm!"
    BG_COLOR: '#12181b'
    FONT_COLOR: '#FFFFFF'
