appName: golden-devops-helm-release

configmap:
  name: golden-devops-helm-release-configmap-v1
  data:
    CUSTOM_HEADER: "This app was deployed with helm!"
    BG_COLOR: "#12181b"
    FONT_COLOR: "#FFFFFF"

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

disableTLS: false
