---
##########################
## Hadolint config file ##
##########################

failure-threshold: warning

ignored:
  - DL3022  # (`COPY --from` should reference a previously defined `FROM` alias)
