---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2 # This tells AWS to send traffic from the ALB using HTTP2. Can use GRPC as well if you want to leverage GRPC-specific features
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
  sessionAffinity: None
  type: NodePort
