---
# Note: Values from this ConfigMap are not used in the container's source code (but they of course can be, then
# just use them in the source code)

kind: ConfigMap 
apiVersion: v1 
metadata:
    name: {{ .Values.configmap.name }}
    namespace: {{ .Values.namespace }}
data:
    BG_COLOR: "{{ .Values.configmap.data.BG_COLOR }}"
    FONT_COLOR: "{{ .Values.configmap.data.FONT_COLOR }}"
    CUSTOM_HEADER: "{{ .Values.configmap.data.CUSTOM_HEADER }}"
