apiVersion: v1
kind: Secret
metadata:
  name: k8-test-apps
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/JakubSzuber/Golden-DevOps.git
