---
# Deploy to every environment

name: CD

concurrency: delivery

on:  # Trigger automatically on integration.yml success (merged pull request or direct push)
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECS_SERVICE: my-service
  ECS_CLUSTER: initial-cluster
  ECS_TASK_DEFINITION: .aws/ecs-task-definition.json
  CONTAINER_NAME: some-nginx
  IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

jobs:
  # TODO use reusable workflow for the change-tag-dev and change-tag-staging jobs
  # Only trigger if the previous workflow run was successful and the event was not a pull request
  change-tag-dev:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event != 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      contents: write    # This is required for actions/checkout
      id-token: write   # This is required for requesting the JWT

    environment: 
      name: Development
      url: https://dev.goldendevops.com/

    steps:
      - name: Print the used tag
        run: echo "To development environment will deploy a container with image tag  sha-${{ env.IMAGE_TAG }}"

      - name: Print the used tag
        run: echo "Changing the image's tag in the manifest to sha-${{ env.IMAGE_TAG }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace image tag  # Git commands require granting the permissions for read and write for the workflow
        run: |
          echo "Helm values-dev.yaml file before change:" && cat helm-charts/main-chart/values-dev.yaml
          sed -i "s/sha-.*/sha-${{ env.IMAGE_TAG }}/" helm-charts/main-chart/values-dev.yaml
          echo "Helm values-dev.yaml file after change:" && cat helm-charts/main-chart/values-dev.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add helm-charts/main-chart/values-dev.yaml
          git commit -m "Update the image's tag in the Helm values-dev.yaml file [skip actions]"
          git push

  change-tag-staging:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event != 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      contents: write    # This is required for actions/checkout
      id-token: write   # This is required for requesting the JWT

    environment: 
      name: Staging
      url: https://staging.goldendevops.com/

    steps:
      - name: Print the used tag
        run: echo "To staging environment will deploy a container with image tag  sha-${{ env.IMAGE_TAG }}"

      - name: Print the used tag
        run: echo "Changing the image's tag in the manifest to sha-${{ env.IMAGE_TAG }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace image tag  # Git commands require granting the permissions for read and write for the workflow
        run: |
          echo "Helm values-staging.yaml file before change:" && cat helm-charts/main-chart/values-staging.yaml
          sed -i "s/sha-.*/sha-${{ env.IMAGE_TAG }}/" helm-charts/main-chart/values-staging.yaml
          echo "Helm values-staging.yaml file after change:" && cat helm-charts/main-chart/values-staging.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add helm-charts/main-chart/values-staging.yaml
          git commit -m "Update the image's tag in the Helm values-staging.yaml file [skip actions]"
          git push

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           role-to-assume: arn:aws:iam::152691795422:role/gh-action-role
#           role-session-name: samplerolesession
#           aws-region: ${{ env.AWS_REGION }}

#  Optionally you can use ECR instead of Docker Hub (then you will have to change a lot in CI and CD workflow)
#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

#       - name: Build, tag, and push image to Amazon ECR
#         id: build-image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           # Build a docker container and
#           # push it to ECR so that it can
#           # be deployed to ECS.
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#           echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

#       - name: Fill in the new image ID in the Amazon ECS task definition
#         id: task-def
#         uses: aws-actions/amazon-ecs-render-task-definition@97587c9d45a4930bf0e3da8dd2feb2a463cf4a3a
#         with:
#           task-definition: ${{ env.ECS_TASK_DEFINITION }}
#           container-name: ${{ env.CONTAINER_NAME }}
#           image: docker.io/jakubszuber/testing_image:sha-${{ env.IMAGE_TAG }}  # Use just created image by the CI workflow

#       - name: Deploy Amazon ECS task definition
#         uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
#         with:
#           task-definition: ${{ steps.task-def.outputs.task-definition }}
#           service: ${{ env.ECS_SERVICE }}
#           cluster: ${{ env.ECS_CLUSTER }}
#           wait-for-service-stability: true

  # TODO add some smoke test maybe by codeguru or just simply use some command that will check the status of the task or do "curl" on container
  change-tag-production:
    runs-on: ubuntu-latest
    needs: [change-tag-staging]

    permissions:
      contents: write

    environment: 
      name: Production
      url: https://goldendevops.com/

    steps:
      - name: Print the used tag
        run: echo "Changing the image's tag in the manifest to sha-${{ env.IMAGE_TAG }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace image tag  # Git commands require granting the permissions for read and write for the workflow
        run: |
          echo "Helm values-prod.yaml file before change:" && cat helm-charts/main-chart/values-prod.yaml
          sed -i "s/sha-.*/sha-${{ env.IMAGE_TAG }}/" helm-charts/main-chart/values-prod.yaml
          echo "Helm values-prod.yaml file after change:" && cat helm-charts/main-chart/values-prod.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add helm-charts/main-chart/values-prod.yaml
          git commit -m "Update the image's tag in the Helm values-prod.yaml file [skip actions]"
          git push

  notify-slack:
    # Setup guide https://github.com/marketplace/actions/slack-send#technique-3-slack-incoming-webhook
    name: Notify Slack
    needs: [change-tag-production]
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event != 'pull_request'
    runs-on: ubuntu-latest
    env: 
      STAT: ${{ needs.change-tag-production.result }}

    # TODO Add here permissions: block

    steps:
      - name: TEST1
        run: |
          if [[ "$STAT" == "skipped" ]]; then
            echo "STAT=failure" >> "$GITHUB_ENV"
          fi

      - name: TEST
        run: |
          echo "$STAT"
          echo ${{ env.STAT }}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.STAT }}
          fields: repo,message,author,commit,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL2 }}
        if: always() # Pick up events even if the job fails or is canceled.
