---
# Workflow responsible for publishing the GitHub release tags

name: Publish GitHub Release

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

permissions:
  contents: write
  discussions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
