name: Helm-Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'helm/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
#        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

#       - name: Create kind cluster
# #        if: steps.list-changed.outputs.changed == 'true'
#         uses: helm/kind-action@v1.4.0
        
      # Run micro Kubernetes cluster for testing purposes
      - uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

      - name: Run chart-testing (install)
#        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Helm resources
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }}
          helm install golden-devops-helm-release helm-chart --values helm-chart/values.yaml -f helm-chart/values-prod.yaml
          echo "Waiting to startup containers..."
          sleep 30
          kubectl get all --namespace=prod-namespace
          echo "---------------------------Main container logs--------------------------"
          kubectl logs -l app=golden-devops-helm-release --namespace=prod-namespace
          echo "------------------------------------------------------------------------"

      - name: Test Helm resources (curl)
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl exec deploy/golden-devops-helm-release --namespace=prod-namespace -- curl --fail localhost || echo "Successfully retrieved data from localhost!"

      - name: Test Helm resources (wget)
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm test golden-devops-helm-release || echo "Testing of Helm golden-devops-helm-release failed!"
          echo "---------------------------Testing container logs--------------------------"
          kubectl logs golden-devops-helm-release-connection-test --namespace=prod-namespace
          echo "---------------------------------------------------------------------------"
