name: Helm-Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'helm/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
#        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
#        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
#        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
        
      - name: TESTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm install golden-devops-helm-release helm-chart --values helm-chart/values.yaml -f helm-chart/values-prod.yaml
          kubectl exec deploy/golden-devops-helm-release --namespace=staging-namespace -- curl --fail localhost || echo "nie1"
          helm test golden-devops-helm-release || echo "Testing of Helm golden-devops-helm-release failed!"
          kubectl logs golden-devops-helm-release-connection-test --namespace=staging-namespace
