---
# Note:
# You can uncomment "if" statements in all steps but by leaving that comments we ensure that each time this workflow will run we will test the Helm 
# chart even if the chart itself hasn't changed. By doing this we ensure that the potentially changed source code still works along with the Helm chart.

name: Helm-Test
# TODO Restrict permissions
# TODO make this workflow universal so it will be able to work for each helm chart within the helm-charts directory
# TODO change this file if you decided to use separete namespace for main application's resources

on:
  workflow_dispatch:  # Step "Run chart-testing (list-changed)" will always return that there are no changes while workflow is executed manually
  pull_request:
    branches: ['main', 'dev_*', 'snyk-upgrade-*']
    paths:
      - 'helm-charts/**'
  push:
    branches: [main]
    paths:
      - 'helm-charts/**'

jobs:
  test-with-commands:
    if: github.event_name != 'push'
    name: Test Using Command-Line Tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run micro Kubernetes cluster for testing purposes
        uses: AbsaOSS/k3d-action@v2
#        if: steps.list-changed.outputs.changed == 'true'
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

      - name: Login to Docker Hub
#        if: steps.list-changed.outputs.changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Helm resources
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }}
          helm install golden-devops-helm-release helm-charts/main-chart --values helm-charts/main-chart/values.yaml -f helm-charts/main-chart/values-prod.yaml --set disableTLS=true
          echo "Waiting to startup containers..."
          sleep 50
          kubectl get all --namespace=argocd
          echo "---------------------------Main container logs--------------------------"
          kubectl logs -l app=golden-devops-helm-release --namespace=argocd
          echo "------------------------------------------------------------------------"

      # TODO Later, when you move from the self-signed certificates delete "-k" flag
      - name: Test Helm resources (curl command)
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          if ! kubectl exec deploy/golden-devops-helm-release --namespace=argocd -- curl -k -f https://localhost:8080; then
            echo "Failed to retrieve data from localhost!"
            exit 1
          fi

      - name: Test Helm resources (wget with testing container)
#        if: steps.list-changed.outputs.changed == 'true'
        run: |
          if ! helm test golden-devops-helm-release; then
            echo "Testing of Helm golden-devops-helm-release failed!"
            echo "---------------------------Testing container logs--------------------------"
            kubectl logs golden-devops-helm-release-connection-test --namespace=argocd
            echo "---------------------------------------------------------------------------"
            exit 1
          fi
          echo "---------------------------Testing container logs--------------------------"
          kubectl logs golden-devops-helm-release-connection-test --namespace=argocd
          echo "---------------------------------------------------------------------------"

  scan-image-Trivy:
    if: github.event_name != 'push'
    name: Scan Helm Chart With Trivy
    runs-on: ubuntu-latest

    permissions:
      contents: read          # Obtain permission needed for actions/checkout to fetch code
      security-events: write  # Obtain permission needed for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82 # tag=v3.4
        with:
          version: v3.6.3

      - name: Set up python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4.3.0
        with:
          python-version: 3.7

      # Gain an additional overview of the vulnerabilities
      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          scan-ref: 'helm-charts/main-chart'
          exit-code: 0
          format: table

      - name: Run Trivy for all CVEs (blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          scan-ref: 'helm-charts/main-chart'
          exit-code: 1
          severity: 'CRITICAL'
          format: table

  test-Snyk:
    if: github.event_name != 'push'
    name: Scan Helm Chart With Snyk
    runs-on: ubuntu-latest

    permissions:
      contents: read          # Obtain permission needed for actions/checkout to fetch code
      security-events: write  # Obtain permission needed for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Template Helm chart's files
        run: |
          cd helm-charts/main-chart
          helm dependency update
          helm template . -f values.yaml -f values-prod.yaml --output-dir rendered-main-chart

      # Gain an additional overview of the vulnerabilities
      - name: Run Snyk to check the Helm chart for vulnerabilities (non-blocking)
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: helm-charts/main-chart/rendered-main-chart

      - name: Run Snyk to check the Helm chart for vulnerabilities (blocking)
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: helm-charts/main-chart/rendered-main-chart
          args: --severity-threshold=critical

  image-scan-results-Trivy:
    if: github.event_name != 'pull_request'
    name: Scan Image With Trivy And Upload Results
    runs-on: ubuntu-latest

    permissions:
      contents: read          # Obtain permission needed for actions/checkout to fetch code
      security-events: write  # Obtain permission needed for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82 # tag=v3.4
        with:
          version: v3.6.3

      - name: Set up python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4.3.0
        with:
          python-version: 3.7

      # Gain an additional overview of the vulnerabilities
      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          scan-ref: 'helm-charts/main-chart'
          exit-code: 0
          format: table

# TODO Trivy reports to GitHub Code Scanning can be uncommented if the
# TODO issue https://github.com/aquasecurity/trivy-action/issues/258 will be fixed
#      - name: Run Trivy for HIGH CVEs and report
#        uses: aquasecurity/trivy-action@master
#        with:
#          scan-type: 'config'
#          hide-progress: false
#          scan-ref: 'helm-charts/main-chart'
#          exit-code: 0
#          ignore-unfixed: true
#          severity: 'HIGH'
#          format: 'sarif'
#          output: 'trivy-results.sarif'
#
#      - name: Upload Trivy scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: 'trivy-results.sarif'

  image-scan-results-Snyk:
    if: github.event_name != 'pull_request'
    name: Scan Helm Chart With Snyk And Upload Results
    runs-on: ubuntu-latest

    permissions:
      contents: read          # Obtain permission needed for actions/checkout to fetch code
      security-events: write  # Obtain permission needed for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Template Helm chart's files
        run: |
          cd helm-charts/main-chart
          helm dependency update
          helm template . -f values.yaml -f values-prod.yaml --output-dir rendered-main-chart

      # Gain an additional overview of the vulnerabilities
      - name: Run Snyk to check the Helm chart for vulnerabilities (non-blocking)
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: helm-charts/main-chart/rendered-main-chart
          args: --report

      - name: Run Snyk for HIGH CVEs and report
        if: github.event_name != 'push'
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: helm-charts/main-chart/rendered-main-chart
          args: --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'snyk.sarif'
