---
# Complete workflow responsible for destroying entire terraform infrastructure

name: Infra-cleanup

concurrency: infra-cleanup

# TODO those event triggers are completely temporary
on:  # TODO Change the trigger events' logic (or leave if you are sure it's ok (but it's probably not)). Maybe do that branch have to start with "dev_" or branch main but only for /src
  workflow_dispatch:
#  push:
#    branches: [main]
#    paths:
#      - 'src/**'
#      - '!src/**/README.md'
#  pull_request:
#    branches: [main]
#    paths:
#      - 'src/**'
#      - '!src/**/README.md'

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

env:
  TF_LOG: INFO
  #AWS_REGION: ${{ secrets.AWS_REGION }}  #?
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

#  test-unit:
#    name: Unit tests in Docker
#    needs: [deploy]
#    runs-on: ubuntu-latest
#
#    permissions:
#      packages: read  # Obtain permission needed to pull docker image to ghcr.io
#
#    steps:
#      - name: Login to ghcr.io registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Unit Testing in Docker
        run: |
          docker run --rm ghcr.io/jakubszuber/react-nginx-image:"$GITHUB_RUN_ID" sh -c "cd /test-app && npm test"
