---
# Complete workflow responsible for destroying entire terraform infrastructure

name: Infrastructure Cleanup

concurrency: infra-cleanup

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws OIDC connection
  contents: read # This is required for actions/checkout

env:
  TF_LOG: INFO
  AWS_REGION: us-east-1

jobs:
  remove-development:
    name: Remove the Development
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: dev
      gh-environment-name: Development
      gh-environment-url: https://dev.goldendevops.com/

  remove-staging:
    needs: [remove-development]
    name: Remove the Staging
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: staging
      gh-environment-name: Staging
      gh-environment-url: https://staging.goldendevops.com/

  remove-production:
    needs: [remove-staging]
    name: Remove the Production
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: prod
      gh-environment-name: Production
      gh-environment-url: https://goldendevops.com/
